-----------------------------------------------------------------------------------------------------------------
-- Cellular Automaton Drums - 8 drum tracks generated by evolving a seed row using an elementary CA rule (0-255)
-----------------------------------------------------------------------------------------------------------------

local gem = require "includes.common"
local widgets = require "includes.widgets"
local resolutions = require "includes.resolutions"

--------------------------------------------------------------------------------
-- Variables
--------------------------------------------------------------------------------

local numTracks = 8
local numSteps = 16
local isPlaying = false
local seqIndex = 0
local playStep = 1

local rule = 90 -- Default Sierpinski rule
local generationGap = 1 -- CA generations between consecutive tracks
local evolveMode = 1 -- 1 = Static, 2 = Evolve, 3 = Mutate
local mutationProbability = 5

local seedPattern = {} -- 16 booleans (the seed row)
local grid = {} -- 8 rows of 16 booleans (the derived drum patterns)
local seedButtons = {} -- UI references for the seed cells
local trackTables = {} -- UI references for the per-track pattern displays
local trackNotes = {}
local trackMutes = {}
local trackListens = {}
local trackLabels = {}
local trackVelocities = {}
local noteListen = nil

-- General MIDI drum map defaults
local defaultNoteMap = {36, 38, 42, 39, 41, 49, 54, 66}
local defaultNoteLabels = {"Kick", "Snare", "Hihat", "Clap", "Low Tom", "Cymbal", "Tambourine", "Perc"}

-- Famous elementary CA rules
local rulePresets = {
  {name = "30 (Chaotic)",       value = 30},
  {name = "90 (Sierpinski)",    value = 90},
  {name = "110 (Universal)",    value = 110},
  {name = "150 (XOR)",          value = 150},
  {name = "184 (Traffic)",      value = 184},
  {name = "18 (Sparse)",        value = 18},
  {name = "54 (Class IV)",      value = 54},
  {name = "60 (Linear)",        value = 60},
  {name = "126 (Triangles)",    value = 126},
  {name = "22 (Fractal)",       value = 22},
}

--------------------------------------------------------------------------------
-- Cellular Automaton Logic
--------------------------------------------------------------------------------

-- Apply elementary CA rule to a 3-cell neighborhood (each cell 0 or 1).
-- Rule is a number 0-255; bit i = output for neighborhood pattern i (0-7).
local function applyRule(left, center, right, ruleValue)
  local idx = (left and 4 or 0) + (center and 2 or 0) + (right and 1 or 0)
  return (math.floor(ruleValue / (2 ^ idx)) % 2) == 1
end

-- Evolve a row once using the current rule. Wraps horizontally (toroidal).
local function evolveRow(row, ruleValue)
  local next = {}
  local n = #row
  for i = 1, n do
    local L = row[((i - 2) % n) + 1]
    local C = row[i]
    local R = row[(i % n) + 1]
    next[i] = applyRule(L, C, R, ruleValue)
  end
  return next
end

-- Apply a small random mutation to a row (each cell has `prob` % chance to flip).
local function mutateRow(row, prob)
  local out = {}
  for i = 1, #row do
    if gem.getRandomBoolean(prob) then
      out[i] = not row[i]
    else
      out[i] = row[i]
    end
  end
  return out
end

-- Rebuild the 8 drum rows by evolving the seed `generationGap` steps per row.
local function rebuildGrid()
  local current = {}
  for i = 1, numSteps do current[i] = seedPattern[i] end
  for track = 1, numTracks do
    for _ = 1, generationGap do
      current = evolveRow(current, rule)
    end
    grid[track] = current
    -- copy so subsequent evolves don't mutate the stored row
    local copy = {}
    for i = 1, numSteps do copy[i] = current[i] end
    current = copy
  end
end

local function refreshDisplay()
  if trackTables[1] == nil then return end
  for track = 1, numTracks do
    for step = 1, numSteps do
      trackTables[track]:setValue(step, grid[track][step] and 1 or 0)
    end
  end
end

local function randomizeSeed()
  for i = 1, numSteps do
    seedPattern[i] = gem.getRandomBoolean(35)
    if seedButtons[i] then seedButtons[i]:setValue(seedPattern[i], false) end
  end
  rebuildGrid()
  refreshDisplay()
end

local function clearSeed()
  for i = 1, numSteps do
    seedPattern[i] = false
    if seedButtons[i] then seedButtons[i]:setValue(false, false) end
  end
  rebuildGrid()
  refreshDisplay()
end

-- Initialise the seed with a single live cell in the middle (classic CA seed)
for i = 1, numSteps do seedPattern[i] = (i == math.floor(numSteps / 2)) end
rebuildGrid()

--------------------------------------------------------------------------------
-- Header Panel
--------------------------------------------------------------------------------

widgets.setColours({
  labelBackgroundColour = "B5C8B0",
  backgroundColour = "2D3142",
})

local sequencerPanel = widgets.panel({
  width = 720,
  height = 30,
})

widgets.label("Cellular Automaton Drums", {
  tooltip = "Eight drum tracks generated by evolving a seed row using an elementary CA rule",
  width = sequencerPanel.width,
  height = 30,
  alpha = 0.5,
  fontSize = 22,
})

widgets.setSection({
  width = 90,
  xOffset = 525,
  yOffset = 5,
  xSpacing = 5,
  ySpacing = 5,
})

local autoplayButton = widgets.button("Auto Play", true, {
  tooltip = "Play automatically when the host transport starts",
})

local playButton = widgets.button("Play", false, {
  tooltip = "Start/stop the sequencer manually",
  changed = function(self)
    if self.value then
      startPlaying()
    else
      stopPlaying()
    end
  end
})

--------------------------------------------------------------------------------
-- Settings Panel
--------------------------------------------------------------------------------

widgets.setSection({ xOffset = 0, yOffset = 0, xSpacing = 0, ySpacing = 0 })

local settingsPanel = widgets.panel({
  x = sequencerPanel.x,
  y = widgets.posUnder(sequencerPanel),
  width = sequencerPanel.width,
  height = 40,
})

widgets.setSection({
  width = 90,
  height = 22,
  xOffset = 5,
  yOffset = 9,
  xSpacing = 5,
  ySpacing = 0,
  cols = 8,
})

local ruleInput = widgets.numBox("Rule", rule, {
  tooltip = "Elementary CA rule (0-255). Each rule defines how each 3-cell neighborhood evolves.",
  min = 0, max = 255, integer = true,
  changed = function(self)
    rule = self.value
    rebuildGrid()
    refreshDisplay()
  end
})

local presetNames = {}
for _, p in ipairs(rulePresets) do table.insert(presetNames, p.name) end
table.insert(presetNames, 1, "Preset...")

widgets.menu("Preset", 1, presetNames, {
  tooltip = "Quick-pick well-known CA rules",
  showLabel = false,
  width = 140,
  changed = function(self)
    if self.value > 1 then
      ruleInput:setValue(rulePresets[self.value - 1].value)
      self.value = 1
    end
  end
})

widgets.menu("Evolution", evolveMode, {"Static", "Evolve", "Mutate"}, {
  tooltip = "Static: seed repeats. Evolve: last row becomes next seed. Mutate: small random flips each bar.",
  showLabel = false,
  width = 90,
  changed = function(self) evolveMode = self.value end
})

widgets.numBox("Mutation", mutationProbability, {
  tooltip = "Per-cell flip probability (%) when Evolution mode is set to Mutate",
  min = 0, max = 100, integer = true, unit = Unit.Percent,
  changed = function(self) mutationProbability = self.value end
})

widgets.numBox("Gen Gap", generationGap, {
  tooltip = "Number of CA generations between adjacent drum tracks (higher = more variation between drums)",
  min = 1, max = 8, integer = true,
  changed = function(self)
    generationGap = self.value
    rebuildGrid()
    refreshDisplay()
  end
})

widgets.button("Random Seed", false, {
  tooltip = "Randomize the seed pattern",
  persistent = false,
  width = 95,
  changed = function(self)
    if self.value then
      randomizeSeed()
      self:setValue(false, false)
    end
  end
})

widgets.button("Clear Seed", false, {
  tooltip = "Clear all cells in the seed pattern",
  persistent = false,
  width = 80,
  changed = function(self)
    if self.value then
      clearSeed()
      self:setValue(false, false)
    end
  end
})

--------------------------------------------------------------------------------
-- Seed Row Panel
--------------------------------------------------------------------------------

widgets.setSection({ xOffset = 0, yOffset = 0, xSpacing = 0, ySpacing = 0 })

local seedPanel = widgets.panel({
  x = sequencerPanel.x,
  y = widgets.posUnder(settingsPanel),
  width = sequencerPanel.width,
  height = 32,
})

widgets.setSection({
  width = 65,
  height = 22,
  xOffset = 5,
  yOffset = 5,
  xSpacing = 0,
  ySpacing = 0,
})

widgets.label("Seed", {
  tooltip = "Generation 0 - the source pattern that all drum tracks are derived from",
})

-- 16 clickable seed cells
widgets.setSection({
  width = 28,
  height = 22,
  xOffset = 76,
  yOffset = 5,
  xSpacing = 2,
  ySpacing = 0,
  cols = numSteps,
})

for i = 1, numSteps do
  seedButtons[i] = widgets.button(tostring(i), seedPattern[i], {
    tooltip = "Step " .. i .. " - click to toggle the seed cell",
    backgroundColourOff = "303040",
    backgroundColourOn = "66FF99",
    textColourOff = "606080",
    textColourOn = "202020",
    changed = function(self)
      seedPattern[i] = self.value
      rebuildGrid()
      refreshDisplay()
    end
  })
end

--------------------------------------------------------------------------------
-- Tracks Panel
--------------------------------------------------------------------------------

widgets.setSection({ xOffset = 0, yOffset = 0, xSpacing = 0, ySpacing = 0 })

local tracksPanel = widgets.panel({
  x = sequencerPanel.x,
  y = widgets.posUnder(seedPanel),
  width = sequencerPanel.width,
  height = numTracks * 28 + 4,
})

local trackColours = {
  "FF6B6B", "FFD93D", "6BCB77", "4D96FF",
  "B983FF", "FF6BCB", "FFA94D", "9DD9D2",
}

for track = 1, numTracks do
  local rowY = 4 + (track - 1) * 28

  -- Track label (editable name)
  widgets.setSection({
    width = 65, height = 22,
    x = 5, y = rowY,
    cols = 1,
  })
  trackLabels[track] = widgets.label(defaultNoteLabels[track], {
    tooltip = "Track " .. track .. " name",
    editable = true,
    backgroundColour = "111111",
    backgroundColourWhenEditing = "white",
    textColourWhenEditing = "black",
    textColour = trackColours[track],
  })

  -- Pattern display table (16 cells)
  widgets.setSection({
    width = 400, height = 22,
    x = 75, y = rowY,
    cols = 1,
  })
  trackTables[track] = widgets.table("Track" .. track, 0, numSteps, {
    enabled = false,
    persistent = false,
    fillStyle = "solid",
    backgroundColour = "191E25",
    sliderColour = trackColours[track],
    min = 0, max = 1, integer = true,
  })

  -- Note input
  widgets.setSection({
    width = 48, height = 22,
    x = 482, y = rowY,
    cols = 1,
  })
  trackNotes[track] = widgets.numBox("Note", defaultNoteMap[track], {
    name = "Note" .. track,
    tooltip = "MIDI note number for " .. defaultNoteLabels[track],
    showLabel = false,
    min = 0, max = 127, integer = true,
  })

  -- Learn
  widgets.setSection({
    width = 36, height = 22,
    x = 534, y = rowY,
    cols = 1,
  })
  trackListens[track] = widgets.button("L", false, {
    name = "Learn" .. track,
    tooltip = "Note learn - play a note to set the track note",
    persistent = false,
    backgroundColourOn = "006600",
    textColourOn = "white",
    changed = function(self)
      if self.value then
        noteListen = track
      elseif noteListen == track then
        noteListen = nil
      end
    end
  })

  -- Mute
  widgets.setSection({
    width = 48, height = 22,
    x = 574, y = rowY,
    cols = 1,
  })
  trackMutes[track] = widgets.button("Mute", false, {
    name = "Mute" .. track,
    tooltip = "Mute " .. defaultNoteLabels[track],
  })

  -- Velocity
  widgets.setSection({
    width = 48, height = 22,
    x = 626, y = rowY,
    cols = 1,
  })
  trackVelocities[track] = widgets.numBox("Vel", 100, {
    name = "Vel" .. track,
    tooltip = "Velocity for " .. defaultNoteLabels[track],
    showLabel = false,
    min = 1, max = 127, integer = true,
  })
end

refreshDisplay()


--------------------------------------------------------------------------------
-- Footer Panel
--------------------------------------------------------------------------------

widgets.setSection({ xOffset = 0, yOffset = 0, xSpacing = 0, ySpacing = 0 })

local footerPanel = widgets.panel({
  x = sequencerPanel.x,
  y = widgets.posUnder(tracksPanel),
  width = sequencerPanel.width,
  height = 40,
})

widgets.setSection({
  width = 110,
  height = 22,
  xOffset = 5,
  yOffset = 9,
  xSpacing = 5,
  ySpacing = 0,
  cols = 8,
})

local resolutionInput = widgets.menu("Resolution", 20, resolutions.getResolutionNames(), {
  tooltip = "Time per step (default 1/8 - one bar of 16 steps = 2 bars at this resolution)",
  showLabel = false,
})

local gateInput = widgets.numBox("Gate", 80, {
  tooltip = "Note length as % of step duration",
  min = 1, max = 200, integer = true, unit = Unit.Percent,
  width = 90,
})

local channelButton = widgets.button("Multichannel", false, {
  tooltip = "When enabled, each track is sent to a separate MIDI channel (track 1 = base channel, track 2 = +1, etc.)",
  width = 110,
})

local channelInput = widgets.numBox("Channel", 1, {
  tooltip = "Base MIDI channel (1-16). In multichannel mode each track uses base + track number - 1.",
  min = 1, max = 16, integer = true,
  width = 90,
})

local stepLabel = widgets.label("Step 1 / " .. numSteps, {
  tooltip = "Current playback position",
  width = 130,
})

--------------------------------------------------------------------------------
-- Sequencer
--------------------------------------------------------------------------------

function startPlaying()
  if isPlaying then return end
  seqIndex = gem.inc(seqIndex)
  isPlaying = true
  run(sequenceRunner, seqIndex)
end

function stopPlaying()
  if isPlaying == false then return end
  isPlaying = false
  playStep = 1
  if stepLabel then stepLabel.text = "Step 1 / " .. numSteps end
end

local function getTrackChannel(track)
  if channelButton.value then
    return ((channelInput.value + track - 2) % 16) + 1
  end
  return channelInput.value
end

local function applyEvolution()
  if evolveMode == 1 then
    return
  elseif evolveMode == 2 then
    -- Use last drum row as new seed
    local lastRow = grid[numTracks]
    for i = 1, numSteps do
      seedPattern[i] = lastRow[i]
      if seedButtons[i] then seedButtons[i]:setValue(seedPattern[i], false) end
    end
  elseif evolveMode == 3 then
    seedPattern = mutateRow(seedPattern, mutationProbability)
    for i = 1, numSteps do
      if seedButtons[i] then seedButtons[i]:setValue(seedPattern[i], false) end
    end
  end
  rebuildGrid()
  refreshDisplay()
end

function sequenceRunner(uniqueId)
  playStep = 1
  while isPlaying and seqIndex == uniqueId do
    local stepDuration = resolutions.getResolution(resolutionInput.value)
    local gate = gateInput.value
    local playDuration = resolutions.getPlayDuration(stepDuration, gate)
    local playDurationMs = beat2ms(playDuration)

    -- Trigger all live cells in this column
    for track = 1, numTracks do
      if trackMutes[track].value == false and grid[track][playStep] then
        local note = trackNotes[track].value
        local velocity = trackVelocities[track].value
        playNote(note, velocity, playDurationMs, nil, getTrackChannel(track))
      end
    end

    if stepLabel then stepLabel.text = "Step " .. playStep .. " / " .. numSteps end

    waitBeat(stepDuration)

    playStep = playStep + 1
    if playStep > numSteps then
      playStep = 1
      applyEvolution()
    end
  end
end

--------------------------------------------------------------------------------
-- Handle Events
--------------------------------------------------------------------------------

function onNote(e)
  if type(noteListen) == "number" then
    trackNotes[noteListen]:setValue(e.note)
    trackListens[noteListen]:setValue(false, false)
    noteListen = nil
  end
  if autoplayButton.value == true then
    postEvent(e)
  else
    playButton:setValue(true)
  end
end

function onRelease(e)
  if autoplayButton.value == true then
    postEvent(e)
  else
    playButton:setValue(false)
  end
end

function onTransport(start)
  if autoplayButton.value == true then
    playButton:setValue(start)
  end
end

--------------------------------------------------------------------------------
-- Save / Load
--------------------------------------------------------------------------------

function onSave()
  local labelData = {}
  for i = 1, numTracks do
    table.insert(labelData, trackLabels[i].text)
  end
  return {labelData}
end

function onLoad(data)
  local labelData = data[1]
  if type(labelData) == "table" then
    for i = 1, math.min(#labelData, numTracks) do
      trackLabels[i].text = labelData[i]
    end
  end
end

